' 基于的RN版本，0.71.4

@startuml Bundle加载时序

participant App
participant NativeModule
participant RCTBridge
participant RCTCxxBridge
participant Instance
participant NativeToJsBridge
participant JSExecutor

note over RCTBridge: 与JS通信用对象
note over RCTCxxBridge: 很多真实操作会从\nRCTBridge代理过来

NativeModule -> NativeModule: RCT_EXPORT_MODULE()导出
note right: 如果实现了RCTTurboModule协议\n则就适配了TurboModule
NativeModule -> RCTBridge: RCTRegisterModule(self)
note right: 在+load()中调用
RCTBridge -> RCTBridge: 存储至RCTModuleClasses中

App -> RCTBridge: createBridge
RCTBridge -> RCTBridge: setUp
RCTBridge -> App: request bundle URL
note right: sourceURLForBridge:
App -> RCTBridge: bundle URL
note right: RCTBundleURLProvider中获取

RCTBridge -> RCTCxxBridge: create

group start
RCTCxxBridge -> RCTCxxBridge: 创建工作线程
RCTCxxBridge -> RCTCxxBridge: 初始化Module/moduleData等
note left: 仅非TurboModule\n才有moduleData
RCTCxxBridge -> RCTCxxBridge: 创建ExecutorFactory
note left: Hermes或JSC

RCTCxxBridge -> RCTCxxBridge: loadSource

    group executeSourceCode
    RCTCxxBridge -> RCTCxxBridge: executeApplicationScript
    RCTCxxBridge -> Instance: loadScript
    Instance -> NativeToJsBridge: loadBundle
    NativeToJsBridge -> NativeToJsBridge: switch ExecutorQueue
    NativeToJsBridge -> JSExecutor: loadBundle
    end

end

@enduml
